### ISSUE TITLE
Link para o email incorreto

### ISSUE THREAD

**Issue by iJhefe** [valdigleis/mypage#1]
**Problema:** Ao colocar no href da ancora apenas o link, ele vai tentar acessar "https://profvaldi.com/pages/valdigleis.costa@univasf.edu.br" em vez de redirecionar para um mailer.

**Resolução:** Adicionar o redirecionador de mail padrão, "mailto:" no href, ficaria algo como

`<a class="reference external" href="mailto:valdigleis.costa@univasf.edu.br">valdigleis.costa at univasf.edu.br</a>`

**Comment by valdigleis** [comment]
Fazia tanto tempo que eu editei essa página que nem vi, os muitos problemas de html e css que a mesma contém. Na verdade, estou migrando do gitlab para o github todos os projetos concluídos e em andamento na esperança de voltar a mexer neles e encontrar erros e problemas, sinta-se a vontade de verificar todos e me indicar erros. Nos próximos dias devo focar para terminar a migração, também tenho que migrar os projetos do grupo de pesquisa ALiCIA (só eu arrumar coragem para isso)!

**Comment by raulpy271** [comment]
Ocorre esse mesmo erro de redirecionamento na seção "Projects"

**Comment by valdigleis** [comment]
Obrigado @raulpy271 pela indicação!
